#+TITLE: ReadMe MSort

* BitCS MSort
*Warning:* Most files use VHDL2008 features!
In order to change all files in the Vivado Project to VHDL2008, search and replace all occurrences of =<FileInfo>= with =<FileInfo SFType​="VHDL2008">=.
With sed simply run:
#+begin_src bash
sed -i 's/<FileInfo>/<FileInfo SFType="VHDL2008>/g' ProjectFile.xpr
#+end_src
** Folder Structure
- src :: vhdl sources.
- sim :: vhdl simulation sources.
- lib :: vhdl library files.
- templates :: Templates for network generating script.
** Network Generator Script
*** Installation
For "netgen.py" to run, install required packages with

#+begin_src bash
pip3 install -r requirements.txt
#+end_src

*** Usage
For list of available components and templates run
#+begin_src bash
python netgen.py list
#+end_src
By appending a specific component name, all generics and ports will be listed.

For generating a network, run netgen with generate.
Example:
#+begin_src bash
python netgen.py generate evenodd --N=10 - shape --shape_type=median --num_outputs= 2 - fill_template --template_name=Network.vhd --cs=BITCS_SYNC - write_template
#+end_src
This will generate a 10-input Odd-Even network with the middle two values as output.

Alternatively run
#+begin_src bash
./build.sh
#+end_src
to build a set of networks from N=4 to 1024.
